### ISSUE TITLE
The use of GSI for IODA file preparation on RDHPCS versus the Cloud

### ISSUE THREAD

**Issue by HenryWinterbottom-NOAA** [frolovsa/UFS-RNR#21]
Is it feasible to pre-process the observations for the JEDI applications on RDHPCS and then push to the cloud considering the following:

- The UFS generates a 9-hour forecast and uses these as first-guess/background to the GSI in order to generate the observation diagnostic files (miter = 0, niter = 1)

- Create concatenated netcdf files containing the diagnostics for each observation type

- Pass the concatenated netcdf files to the JEDI IODA-converters

What is the GSI doing in this step? Gross-error checking (a sanity check) or is it computing the OMF to be used by the JEDI to compute the increments? If the latter, this implies that the JEDI is really only using the OMF stats to compute the analysis increments and thus could be introducing a bias because of a different background.

Therefore, if the JEDI is just computing the increment, is it valid to pre-process the observations on HPC since the first-guess/background coming from the cycling UFS will be different than that used on the RDHPCS machine to generate the IODA files?

A possible "work-around" would be to pass files between RDHPCS and the cloud (Steve mentioned boto3) such that the GSI sees the same background as the JEDI. However, this seems inefficient and could possibly be more time consuming that just doing the pre-processing on the cloud.

**Comment by jswhit** [comment]
Do we want to turn off

1) observation thinning for radiances?
2) background check that tosses. obs if they are too far from the background?

**Comment by HenryWinterbottom-NOAA** [comment]
@jswhit sure. I will let you know what I learn. We can also chat more at our larger team meeting on Wednesday.
