### ISSUE TITLE
Deterministic/control and ensemble member UFS-RNR atmosphere forecast initial conditions

### ISSUE THREAD

**Issue by HenryWinterbottom-NOAA** [frolovsa/UFS-RNR#25]
Need to add method to generate initial conditions for the UFS-RNR deterministic/control and ensemble member forecasts; no methods yet exist for the ocean/ice models other than spinning the respective fluids up from climatology (e.g., rest).

**Comment by frolovsa** [comment]
@HenryWinterbottom-NOAA, Phil mentioned that folks at GMU have codes to use ECMWF ORAS reanalysis to initialize ocean/ice in the  UFS. Maybe we can learn from them? Henry, do you want to start this conversation thread? 

To generate ensembles (at least for the ocean), we can use "generate perturbations" code in JEDI. Travis can help with that.

**Comment by HenryWinterbottom-NOAA** [comment]
@frolovsa I think this is a good idea. Having all of these capabilities "under one roof" will serve us better in the longer run (in my opinion).

Can you send me the points of contact and I will begin the thread(s). Thanks!

**Comment by frolovsa** [comment]
@HenryWinterbottom-NOAA , ask Phil.

**Comment by HenryWinterbottom-NOAA** [comment]
The GSI can only be used for atmosphere applications and does not require the ocean or ice states other than as boundary conditions (if applicable) for the UFS model. If running in _atmosphere-only_ mode, the ocean and ice states do not matter.

The current biggest computational bottle-neck for this this application of the GSI is the ENKF calculation. The ensemble mean, hybrid gain, and ensemble re-centering (in total) only take about 6-seconds of wall-clock. The ENKF takes on the order of 20-minutes. This can be reduced with more cores, but this remains the most expensive aspect of the UFS-RNR GSI LETKF application.
