### ISSUE TITLE
GSI LETKF within workflow

### ISSUE THREAD

**Issue by HenryWinterbottom-NOAA** [frolovsa/UFS-RNR#26]
Will need ICs for the deterministic and ensemble member forecasts; using the ensemble member forecasts, the GSI will be used to compute the OMF statistics (e.g., GSI diag-formatted files) and then apply these using the NCEP ENKF LETKF capabilities; these respective ensemble members will also be used to construct the flow-dependent covariance matrix in order to update the deterministic/control forecast background; currently, there are no plans to run longer (e.g., > 9-hour) deterministic forecasts.

**Comment by frolovsa** [comment]
For longer forecasts, it might be worth-while adding a separate task for running long forecasts.

**Comment by HenryWinterbottom-NOAA** [comment]
@frolovsa This is coming shortly in a PR. I agree 100%.
